server:
  port: 8099
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: userInfo-server
          uri: lb://userInfo-server
          predicates:
            - Path=/api/v2/userInfo/**
          filters:
            - StripPrefix=2
        - id: passport-server
          uri: lb://passport-server
          predicates:
            - Path=/api/v2/passport/**
          filters:
            - StripPrefix=2
        - id: fans-server
          uri: lb://fans-server
          predicates:
            - Path=/api/v2/fans/**
          filters:
            - StripPrefix=2
        - id: msg-server
          uri: lb://msg-server
          predicates:
            - Path=/api/v2/msg/**
          filters:
            - StripPrefix=2
        - id: vlog-server
          uri: lb://vlog-server
          predicates:
            - Path=/api/v2/vlog/**
          filters:
            - StripPrefix=2
        - id: comment-server
          uri: lb://comment-server
          predicates:
            - Path=/api/v2/comment/**
          filters:
            - StripPrefix=2
  application:
    name: gateway-server
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
  datasource: # 数据源的相关配置
    url: jdbc:mysql://127.0.0.1:3306/media-v2?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456

