# 设置日志级别
logging:
  level:
    root: info
server:
  port: 9001
spring:
  application:
    name: service-user
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/media