server:
  port: 9001
spring:
  application:
    name: service-ucenter
  datasource:
    url: jdbc:mysql://localhost:3306/media-v2
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848